### ISSUE TITLE
Missing BAG files

### ISSUE THREAD

**Issue by eld4niz** [UTS-RI/IDMP#1]
Can you please provide bag file for the launch files? I'm trying to run an experiment, but most of the launch files returns "bag file not found error"

**Comment by eld4niz** [comment]
@Usaali you're providing bag files from your local path, so I can't access these bag files

**Comment by Usaali** [comment]
Hi, sorry for the delay. I updated the launch files and README with information on how to run the bags.

**Comment by eld4niz** [comment]
Thanks for the quick reply and addition to the repo. I successfully ran my experiment.
